### PR TITLE
Implement scheduler basic functionality

### PR DESCRIPTION
**Pull request by panerorenn9541**
Design scheduler that passes all unit tests

### CODE REVIEW

**Review by huzcn — COMMENTED** [review]
This project is primarily to learn how to write tests. Are you sure that every piece of new code is covered in the corresponding test? If not, try to add more tests to maximize coverage.

**Comment by panerorenn9541** [comment]
The first part of this project is to create an algorithm that solves all of the test cases that were provided to us, which is what this PR is for. The next part is to create more tests and to add more to the initial functionality, and this is what I am currently working on.

**Comment by huzcn** [comment]
> The first part of this project is to create an algorithm that solves all of the test cases that were provided to us, which is what this PR is for. The next part is to create more tests and to add more to the initial functionality, and this is what I am currently working on.

Starting from this project, I would like to see all new code come together with the detailed tests, which should be in the same pull request. I think the tutorial also implicitly indicates this: the step of sending PR comes after writing more tests
https://github.com/panerorenn9541/step/blob/master/walkthroughs/week-5-tdd/project/calendar-walkthrough.md#pull-request

**Comment by huzcn** [comment]
> The first part of this project is to create an algorithm that solves all of the test cases that were provided to us, which is what this PR is for. The next part is to create more tests and to add more to the initial functionality, and this is what I am currently working on.

Starting from this project, I would like to see all new code come together with the detailed tests, which should be in the same pull request. I think the tutorial also implicitly indicates this: the step of sending PR comes after writing more tests
https://github.com/panerorenn9541/step/blob/master/walkthroughs/week-5-tdd/project/calendar-walkthrough.md#pull-request

**Pull request closed without merging**
